# https://github.com/marketplace/actions/publish-to-npm

name: Publish to Github Package Repository
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  gpr-publish:
    if: startsWith(github.ref, 'refs/tags')
    name: gpr-publish
    runs-on: ubuntu-latest
    steps:
      - name: Version
        id: get_version
        run: echo ::set-output name=SEMVER::${GITHUB_REF#refs/tags/v}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn set version classic
      - run: yarn publish --non-interactive --new-version $SEMVER
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEMVER: ${{ steps.get_version.outputs.SEMVER }}
